blank_issues_enabled: false
contact_links:
  - name: "ðŸ’¬ Questions / Discussions"
    url: https://github.com/incial/Incial-web/discussions
    about: Ask questions or start a discussion instead of opening an issue.
